name: shimmer_animation
description: This shimmer animation widget can help you bring simple yet beautiful skeleton loaders to your project with ease.
version: 2.1.0+1
#author: maddyb99 <maddybcorp@outlook.com>
homepage: https://github.com/maddyb99/shimmer_animation

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
